# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbank.proto\"C\n\x04\x42\x61nk\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08initials\x18\x03 \x01(\t\x12\r\n\x05swift\x18\x04 \x01(\t\"\x1c\n\x05\x42\x61nks\x12\x13\n\x04list\x18\x01 \x03(\x0b\x32\x05.Bankb\x06proto3'
)




_BANK = _descriptor.Descriptor(
  name='Bank',
  full_name='Bank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Bank.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='Bank.code', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initials', full_name='Bank.initials', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='Bank.swift', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=81,
)


_BANKS = _descriptor.Descriptor(
  name='Banks',
  full_name='Banks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='Banks.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=111,
)

_BANKS.fields_by_name['list'].message_type = _BANK
DESCRIPTOR.message_types_by_name['Bank'] = _BANK
DESCRIPTOR.message_types_by_name['Banks'] = _BANKS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bank = _reflection.GeneratedProtocolMessageType('Bank', (_message.Message,), {
  'DESCRIPTOR' : _BANK,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:Bank)
  })
_sym_db.RegisterMessage(Bank)

Banks = _reflection.GeneratedProtocolMessageType('Banks', (_message.Message,), {
  'DESCRIPTOR' : _BANKS,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:Banks)
  })
_sym_db.RegisterMessage(Banks)


# @@protoc_insertion_point(module_scope)
